"""add_indexes_optimization

Revision ID: 21c66c826302
Revises: 822629297966
Create Date: 2026-07-03 08:39:58.199094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c66c826302'
down_revision: Union[str, None] = '822629297966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_archivos_activo'), 'archivos', ['activo'], unique=False)
    op.create_index(op.f('ix_archivos_tipo'), 'archivos', ['tipo'], unique=False)
    op.create_index(op.f('ix_clientes_estado'), 'clientes', ['estado'], unique=False)
    op.create_index(op.f('ix_cronograma_prestamo_id'), 'cronograma', ['prestamo_id'], unique=False)
    op.create_index(op.f('ix_facturas_cliente_id'), 'facturas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_facturas_fecha'), 'facturas', ['fecha'], unique=False)
    op.create_index(op.f('ix_logs_modulo'), 'logs', ['modulo'], unique=False)
    op.create_index(op.f('ix_logs_usuario_id'), 'logs', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_pagos_fecha_pago'), 'pagos', ['fecha_pago'], unique=False)
    op.create_index(op.f('ix_pagos_prestamo_id'), 'pagos', ['prestamo_id'], unique=False)
    op.create_index(op.f('ix_prestamos_cliente_id'), 'prestamos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_prestamos_fecha_proximo_pago'), 'prestamos', ['fecha_proximo_pago'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prestamos_fecha_proximo_pago'), table_name='prestamos')
    op.drop_index(op.f('ix_prestamos_cliente_id'), table_name='prestamos')
    op.drop_index(op.f('ix_pagos_prestamo_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_fecha_pago'), table_name='pagos')
    op.drop_index(op.f('ix_logs_usuario_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_modulo'), table_name='logs')
    op.drop_index(op.f('ix_facturas_fecha'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cliente_id'), table_name='facturas')
    op.drop_index(op.f('ix_cronograma_prestamo_id'), table_name='cronograma')
    op.drop_index(op.f('ix_clientes_estado'), table_name='clientes')
    op.drop_index(op.f('ix_archivos_tipo'), table_name='archivos')
    op.drop_index(op.f('ix_archivos_activo'), table_name='archivos')
    # ### end Alembic commands ###
