"""add_intentos_fallidos_bloqueo

Revision ID: 822629297966
Revises: 4a2f89a4a931
Create Date: 2026-07-03 01:25:53.970092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822629297966'
down_revision: Union[str, None] = '4a2f89a4a931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('intentos_fallidos', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('usuarios', sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'bloqueado_hasta')
    op.drop_column('usuarios', 'intentos_fallidos')
    # ### end Alembic commands ###
